version: '3'

services:
  frontend:
    build: frontend
    ports:
      - "3000:80"
  
  backend:
    build: backend
    ports:
      - "3001:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db"]
      interval: 10s
      timeout: 5s
      retries: 5